### ISSUE TITLE
disableDefaultIngress

### ISSUE THREAD

**Issue by stv2509** [keycloak/keycloak-k8s-resources#2]
### Describe the bug

[disableDefaultIngress](https://github.com/keycloak/keycloak-k8s-resources/blob/main/kubernetes/keycloaks.k8s.keycloak.org-v1.yml#L2762)

My keycloack-deployment:

```
---
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
  namespace: keycloak
spec:
  instances: 1
  disableDefaultIngress: true
...
...
```

```
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "disableDefaultIngress" (class org.keycloak.operator.v2alpha1.crds.KeycloakSpec), not marked as ignorable (7 known properties: "defaultIngressDisabled", "serverConfiguration", "unsupported", "image", "instances", "hostname", "tlsSecret"])
 at [Source: UNKNOWN; byte offset: #UNKNOWN] (through reference chain: org.keycloak.operator.v2alpha1.crds.Keycloak["spec"]->org.keycloak.operator.v2alpha1.crds.KeycloakSpec["disableDefaultIngress"])
```

### Version

18.0.0

### Expected behavior

Disable Default Nginx-Ingress

### Actual behavior

Error-log in keycloack-operator:
(7 known properties: "**defaultIngressDisabled**", "serverConfiguration", "unsupported", "image", "instances", "hostname", "tlsSecret"])
